require conf/distro/include/yocto-uninative.inc
require conf/distro/include/security_flags.inc

DISTRO = "hm-generic-console"
DISTRO_NAME = "Host monitor generic console only distro"
DISTRO_VERSION ?= "5.0.7"
DISTRO_CODENAME = "scratchgap"
PACKAGE_CLASSES ?= "package_ipk"
DISTRO_FEATURES = "ipv4 ipv6 systemd usrmerge"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "wifi usbgadget usbhost vfat rtc"

VIRTUAL-RUNTIME_init_manager = "systemd"
PREFERRED_PROVIDER_udev = "systemd"
PREFERRED_PROVIDER_udev-utils = "systemd"
