require conf/distro/include/yocto-uninative.inc
require conf/distro/include/security_flags.inc

DISTRO = "hm-generic-console"
DISTRO_NAME = "Host monitor generic console only distro"
DISTRO_VERSION ?= "5.0.7"
DISTRO_CODENAME = "scratchgap"
PACKAGE_CLASSES ?= "package_ipk"
DISTRO_FEATURES = "ipv4 ipv6 systemd usrmerge"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "wifi usbgadget usbhost vfat rtc"

VIRTUAL-RUNTIME_init_manager = "systemd"
PREFERRED_PROVIDER_udev = "systemd"
PREFERRED_PROVIDER_udev-utils = "systemd"

EXTRA_IMAGE_FEATURES += "allow-root-login"

INHERIT += "extrausers"
EXTRA_USERS_PARAMS = "usermod -p '\$6\$I9buqm178Qc8/Hzv\$Y4MEyax.wBDk6cDfyQKbQUcFabIvI.CUyEfRz/x4x.r5gmnQ/PO5ECSxO73b4XMo5YyD5em.HxiYH0iWa7Kxr1' root;"

PREFERRED_VERSION_libgpiod = "1.6%"

#snögubbe